[package]
name = "dockerstrator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dockerstrator"
path = "src/main.rs"

[dependencies]
inquire = "0.7"
colored = "2.1"
crossterm = "0.25"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
